Override pages guide
tu-graz-library/docs-repository pull request #13
Opened 2021-08-17 08:56 UTC by rekt-hard

closes tu-graz-library/invenio-theme-tugraz/issues/237

2021-08-17 09:16 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding to webpack
```suggestion
#### Update webpack
```

2021-08-17 09:29 UTC, mb-wali requested changes

2021-08-17 09:29 UTC, mb-wali commented on docs/configs/override-pages.md
> +
```suggestion
We will look into - how to override some essential pages of `invenio-app-rdm` with our existing module `invenio-theme-tugraz`
```

2021-08-17 09:29 UTC, mb-wali commented on docs/configs/override-pages.md
> +};
this does not make sense - if this belongs to the override of the search page - add it to the section.

2021-08-17 10:18 UTC, mb-wali requested changes

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +
add this at end

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Creating Search App
```suggestion
### Creating Search App
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Update webpack
```suggestion
### Update webpack
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Override Config Variable
```suggestion
### Override Config Variable
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Update webpack
```suggestion
### Update webpack
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding Search Template
```suggestion
### Adding Search Template
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding Render Function
```suggestion
### Adding Render Function
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding URL Route
```suggestion
### Adding URL Route
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding Render Function
```suggestion
### Adding Render Function
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding URL Route
```suggestion
### Adding URL Route
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Update webpack
```suggestion
### Update webpack
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding Deposit Template
```suggestion
### Adding Deposit Template
```

2021-08-17 10:18 UTC, mb-wali commented on docs/configs/override-pages.md
> +#### Adding URL Route
```suggestion
### Adding URL Route
```

2021-08-17 11:24 UTC, rekt-hard commented on docs/configs/override-pages.md
> +
also added for other pages

2021-08-18 08:56 UTC, mb-wali commented on docs/configs/override-pages.md
> +```
```suggestion
```diff
{%- block javascript %}
    {{ super() }}
-   {{ webpack['invenio-app-rdm-search.js'] }}
+   {{ webpack['invenio-theme-tugraz-rdm-search.js'] }}
{%- endblock %}
```

2021-08-18 08:59 UTC, mb-wali commented on docs/configs/override-pages.md
> +```
```suggestion
```diff
{%- block javascript %}
  {{ super() }}
-  {{ webpack['invenio-app-rdm-user-records-search.js'] }}
+  {{ webpack['invenio-theme-tugraz-rdm-user-records-search.js'] }}
{%- endblock javascript %}
```
```

2021-08-18 09:03 UTC, mb-wali commented on docs/configs/override-pages.md
> +@login_required
add all required import if there is any.

2021-08-18 09:06 UTC, mb-wali requested changes
All looks good! add the changes requsted.

2021-09-01 07:42 UTC, mb-wali approved these changes

2021-09-01 07:43 UTC, merged